package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class CursoRepositoryDB implements CursoRepository{

    //CAMPOS VALIDOS PARA ORDENAR
    private static final Set<String> CAMPO_VALIDOS = Set.of("id","nombre","activo");
    private static final Set<String> ORDEN_VALIDO = Set.of("ASC","DESC");

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass){
        this.url = url;
        this.user = user;
        this.pass = pass;
    }



    private final Connection getConnetion() throws SQLException {

        return DriverManager.getConnection(url,user,pass);
    }

    //métodos

    @Override
    public void intSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS curso (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(100) NOT NULL,
                  activo BOOLEAN  NOT NULL DEFAULT TRUE
                );
                """;
        try{
            Connection c = getConnetion();
            Statement st = c.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("error para crear tabla " + e);
        }

    }

    public void crearCurso(Curso curso){
        if(curso == null){}

        String sql = "INSERT INTO cursos (id, nombre, activo) VALUES(?,?,?)";
        try( Connection con = getConnetion();
                PreparedStatement ps = con.prepareStatement(sql)){
            ps.setInt(1, curso.getId());
            ps.setString(2, curso.getNombre());
            ps.setBoolean(3, curso.isEstado());
            ps.executeUpdate();

        }catch(SQLException e){

            throw new RuntimeException("Error al crear el curso: " + e.getMessage());
        }


    }

    @Override
    public void activar(int id) {
        String sql = "UPDATE cursos SET activo = TRUE WHERE id = ?";
        try (Connection con = getConnetion();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error al activar el curso con id: " + id, e);
        }
    }

    @Override
    public void eliminarSiNombreContiene(String texto) {
        String sql = "DELETE FROM cursos WHERE nombre LIKE ?";

        try(Connection con = getConnetion();
        PreparedStatement ps = con.prepareStatement(sql)){
            ps.setString(1, "%"+texto+"%");
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("se eliminará el curso que contiene el siguiente texto: " +  texto);
        }


    }

    @Override
    public List<Curso> listarPorEstado(boolean activo) {

        String sql = "SELECT id, nombre, estado FROM curso WHERE activo = ?";

        List<Curso> listarPorEstado =  new ArrayList<>();
        try(Connection con = getConnetion();
        PreparedStatement ps = con.prepareStatement(sql)){
            ps.setBoolean(1, activo);
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                Curso curso = new Curso(
                        rs.getInt("id"),
                        rs.getString("nombre"),
                        rs.getBoolean("activo")
                );
                listarPorEstado.add(curso);
            }
        }catch (SQLException e){
            throw new RuntimeException("error al listar cursos por estado",  e);
        }
        return listarPorEstado;
    }

    @Override
    public List<Curso> listarOrdenadoPor(String campo, String orden) {

        if(!CAMPO_VALIDOS.contains(campo)){
            throw new IllegalArgumentException("Campo no valido: " + campo);
        }
        if(!orden.contains(orden.toUpperCase())){
            throw new IllegalArgumentException("orden o valido: " + orden);
        }

        String sql = "SELECT id, nombre, activo FROM cursos ORDR ORDER BY " + campo +" " + orden.toUpperCase();

        List<Curso> listaCurso = new ArrayList<>();

        try(Connection con = getConnetion();
        PreparedStatement pr = con.prepareStatement(sql)){
            ResultSet rs = pr.executeQuery();
            while(rs.next()){
                Curso curso = new Curso(
                rs.getInt("id"),
                rs.getString("nombre"),
                rs.getBoolean("activo")
                );
                listaCurso.add(curso);
            }
        } catch (SQLException e) {
            throw new RuntimeException("error al listar cursos ordenado por: " + e);
        }
        return listaCurso;
    }

}
